URL validation before creating shortlink
VandyHacks/vhl.ink pull request #5
Opened 2021-03-06 23:29 UTC by aadibajpai

Calls the URL object constructor which would throw a type error if it is not a valid url (including if it doesn't begin with a protocol).

Saves us from using regex

2021-03-07 01:04 UTC, leonm1 approved these changes
LGTM. Tested?

2021-03-07 01:09 UTC, SamLee514 approved these changes
nice

2021-03-07 08:33 UTC, Ace314159 requested changes
I found [this SO post](https://stackoverflow.com/a/43467144/3822157) that implies that this doesn't check if these are http/https urls. I think we should only allow those.

2021-03-07 23:39 UTC, aadibajpai commented
> I found [this SO post](https://stackoverflow.com/a/43467144/3822157) that implies that this doesn't check if these are http/https urls. I think we should only allow those.

I did notice that, but since this is an internal tool I'd rather keep it. I was thinking might be an interesting feature tbh if we can do something cool with it.

2021-03-08 01:24 UTC, Ace314159 approved these changes
Sounds good. Just wanted to make sure you were aware of that.

2021-03-10 22:04 UTC, merged

2021-03-10 22:07 UTC, aadibajpai commented
> LGTM. Tested?

yep :)